services:
  - type: web
    name: chatbot-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_web:app
    envVars:
      - key: PORT
        value: "10000"
      - key: PYTHON_VERSION
        value: "3.11.4"
    plan: free
    autoDeploy: true
