services:
  - type: web
    name: chatbot-app
    env: python
    region: oregon # hoặc "frankfurt" nếu bạn ở châu Âu
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app_web.py"
    plan: free
    autoDeploy: true
