services:
  - type: web
    name: chatbot-app
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python ./app_web.py"
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
