services:
  - type: web
    name: chatbot-flask
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
services:  - type: web    name: chatbot-flask    env: python    buildCommand: pip install -r requirements.txt    startCommand: python app.py    envVars:      - key: PORT        value: 10000 
